name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"
  push:
    branches: [ develop ]

env:
  MAJOR_VER: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
          echo "storeFilePath=keystore.jks" > signing.properties
          echo "storePassword=$RELEASE_KEYSTORE_PASSWORD" >> signing.properties
          echo "keyPassword=$RELEASE_KEY_PASSWORD" >> signing.properties
          echo "keyAlias=$RELEASE_KEYSTORE_ALIAS" >> signing.properties
          echo "versionCode=${{ github.run_number }}" >> signing.properties
          echo "versionName=${{ github.run_number }}" >> signing.properties
      - name: Build Release bundle
        run: ./gradlew bundleRelease --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab
